[env]
AWS_PROFILE = "hostahtml"
GOOGLE_CLIENT_ID = "381362730003-92cflufk1gn78o1ir41t9i2tt97dd26q.apps.googleusercontent.com"
PUBLIC_GOOGLE_CLIENT_ID = "381362730003-92cflufk1gn78o1ir41t9i2tt97dd26q.apps.googleusercontent.com"